### ISSUE TITLE
Can't find documentation on the new SSH  port

### ISSUE THREAD

**Issue by marcoedelman** [Zackptg5/Wireguard-Pi-Hole-Cloudflared-Unbound-DNSCrypt-VPN-Server#3]
The installation instructions mentions the changing of the SSH port for security reasons, but since it is the best way for me to connect to the machine, I'd like to know what it's been changed to.

**Comment by Zackptg5** [comment]
It's under the options at the top of the readme. sshport is one of the variables at the top of the VPS_Setup script that you can change. Default ssh port is 22, I have the script change it to 1024 currently but you can change it to whatever (but you won't want to change to a commonly used port or a port used by something else in the script

**Comment by marcoedelman** [comment]
Thanks for that, for some reason I can't seem to use SSH after installation even when using that port. I just get a time-out every time. Any idea what might be causing it? It's literally a matter of "before running the first script SSH works, after full installation SSH times out".

**Comment by Zackptg5** [comment]
Ya, if you can't access a port, it's probably a firewall issue. I use ufw in the script because it's super easy :)
