### ISSUE TITLE
Pihole

### ISSUE THREAD

**Issue by zomboto** [Zackptg5/Wireguard-Pi-Hole-Cloudflared-Unbound-DNSCrypt-VPN-Server#7]
Hey Zackptg5, I want to ask you a question not specifically about this project but closely related. Am I allowed to email you or is there another method of contact where I can reach you? Its pihole, unbound, searx related just not exactly about this project. Thank you.

**Comment by Zackptg5** [comment]
Telegram would be preferred - my username is Zackptg5
